apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rabbitmq

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- storage-class.yaml
- statefulset.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: rabbitmq
  project: fiap-hack
  component: message-queue 