apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq
type: Opaque
data:
  # admin:admin123 (base64 encoded)
  username: YWRtaW4=
  password: YWRtaW4xMjM=
  erlang-cookie: U1ZDUkFITU5VVEVSU0VDUkVU 